routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


/** Rotas para usuários autenticados */
Route::middleware('auth')->group(function () {

    /** Rotas para painel administrativo */
    Route::prefix('admin')->group(function () {

        Route::get('home', 'HomeController@index')->name('home');

        /** Rotas para Event */
        Route::prefix('event')->name('event.')->group(function () {
            Route::get('/', 'EventController@index')->name('index');
            Route::get('/create', 'EventController@create')->name('create');
            Route::post('/store', 'EventController@store')->name('store');
            Route::get('/edit/{event}', 'EventController@edit')->name('edit');
            Route::put('/update/{event}', 'EventController@update')->name('update');
            Route::delete('/destroy/{event}', 'EventController@destroy')->name('destroy');
            Route::get('/show/{event}', 'EventController@show')->name('show');
        });

        /** Rotas para Subscribe */
        Route::prefix('subscribe')->name('subscribe.')->group(function () {
            Route::get('/', 'SubscribeController@index')->name('index');
            Route::get('/show/{subscribe}', 'SubscribeController@show')->name('show');
        });
    });
});

/** Rotas públicas */
Route::prefix('web')->group(function () {

    /** Rotas para Subscribe */
    Route::prefix('subscribe')->name('subscribe.')->group(function () {
        Route::get('/create', 'SubscribeController@create')->name('create');
        Route::post('/store', 'SubscribeController@store')->name('store');
    });
});

app/Models/Event.php
<?php

namespace Descolado\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Event extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'edition',
        'name',
        'description',
        'event_day',
        'subscribe_begin',
        'subscribe_end',
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    public function subscribes()
    {
        return $this->belongsToMany(Subscribe::class, 'subscribe_events');
    }
}

app/Http/Controllers/EventController.php
<?php

namespace Descolado\Http\Controllers;

use Descolado\Http\Controllers\Controller;
use Descolado\Http\Requests\EventRequest;
use Descolado\Services\EventService;
use Descolado\Interfaces\Repositories\EventRepositoryInterface;

class EventController extends Controller
{

    /**
     * @var EventRepositoryInterface
     */
    protected $repository = null;
    /**
     * @var EventService
     */
    private $service = null;

    /**
     * EventController constructor.
     * @param EventRepositoryInterface $repository
     * @param EventService $service
     */
    public function __construct(EventRepositoryInterface $repository, EventService $service)
    {
        $this->repository = $repository;
        $this->service = $service;
    }

    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        $events = $this->repository->getAllEvents();

        return view('admin.event.index', compact('events'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.event.create');
    }


    /**
     * @param EventRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(EventRequest $request)
    {
        try {
            $this->service->createEvent($request);
        } catch (\Exception $e) {
            throw new $e->getMessage();
        }

        return redirect()->route('event.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $event = $this->repository->getEventById($id);

        return view('admin.event.list', compact('event'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function edit($id)
    {
        $event = $this->repository->getEventById($id);

        return view('admin.event.edit', compact('event'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param EventRequest $request
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(EventRequest $request, $id)
    {
        try {
            $this->service->updateEvent($request, $id);
        } catch (\Exception $e) {
            throw new $e->getMessage();
        }

        return redirect()->route('event.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        try {
            $this->service->deleteEvent($id);
        } catch (\Exception $e) {
            throw new $e->getMessage();
        }

        return redirect()->route('event.index');
    }
}

resources/views/admin/event/_form.blade.php
<div class="form-group row">
    {!! Form::label('edition', 'Edição', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::number('edition', null, ['class' => 'form-control' . (!empty($errors->first('edition')) ? ' is-invalid' : ''), 'autofocus']) !!}
        @include('layouts._errors', ['field' => 'edition'])
    </div>
</div>

<div class="form-group row">
    {!! Form::label('name', 'Nome', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::text('name', null, ['class' => 'form-control' . (!empty($errors->first('name')) ? ' is-invalid' : ''), 'autofocus']) !!}
        @include('layouts._errors', ['field' => 'name'])
    </div>
</div>

<div class="form-group row">
    {!! Form::label('description', 'Descrição', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::text('description', null, ['class' => 'form-control' . (!empty($errors->first('description')) ? ' is-invalid' : ''), 'autofocus']) !!}
        @include('layouts._errors', ['field' => 'description'])
    </div>
</div>

<div class="form-group row">
    {!! Form::label('event_day', 'Data do Evento', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::date('event_day', null, ['class' => 'form-control' . (!empty($errors->first('event_day')) ? ' is-invalid' : ''), 'autofocus']) !!}
        @include('layouts._errors', ['field' => 'event_day'])
    </div>
</div>

<div class="form-group row">
    {!! Form::label('subscribe_begin', 'Data Início das Inscrições', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::date('subscribe_begin', null, ['class' => 'form-control' . (!empty($errors->first('subscribe_begin')) ? ' is-invalid' : ''), 'autofocus']) !!}
        @include('layouts._errors', ['field' => 'subscribe_begin'])
    </div>
</div>

<div class="form-group row">
    {!! Form::label('subscribe_end', 'Data Fim das Inscrições', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::date('subscribe_end', null, ['class' => 'form-control' . (!empty($errors->first('subscribe_end')) ? ' is-invalid' : ''), 'autofocus']) !!}
        @include('layouts._errors', ['field' => 'subscribe_end'])
    </div>
</div>

resources/views/admin/event/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">

            {!! Form::open(['route' => 'event.store']) !!}

            @include('admin.event._form')

                <div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        {!! Form::submit('Cadastrar', ['class' => 'btn btn-primary']) !!}
                        <a href="{{ route('event.index') }}" class="btn btn-dark">Cancelar</a>
                    </div>
                </div>

            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/admin/event/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">

                {!! Form::model($event, ['route' => ['event.update', $event->id], 'method' => 'POST']) !!}
                @method('PUT')

                @include('sunset.admin.event._form')

                <div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        {!! Form::submit('Alterar', ['class' => 'btn btn-warning']) !!}
                        <a href="{{ route('event.index') }}" class="btn btn-dark">Cancelar</a>
                    </div>
                </div>

                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/event/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @includeIf('layouts._confirmation-modal')
    <a class="btn btn-sm btn-success mb-1" data-toggle="tooltip" data-placement="top" title="Cadastrar novo evento"
        role="button" href="{{ route('event.create') }}">
        <i class="fas fa-plus-circle"></i>
        Cadastrar novo evento
    </a>
    @if($events->count() > 0)
    <table class="table table-striped table-sm">
        <thead class="thead-dark">
            <tr>
                <th scope="col" class="text-center">#</th>
                <th scope="col" class="text-center">Evento</th>
                <th scope="col" class="text-center">Data</th>
                <th scope="col" class="text-center">Quantidade de Inscritos</th>
                <th scope="col" class="text-center">Período de Inscrição</th>
                <th scope="col" class="text-center">Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($events as $event)
            <tr>
                <th scope="row" class="text-center">{{ $event->id }}</th>
                <td class="text-center">{{ eventName($event->edition, $event->name) }}</td>
                <td class="text-center">{{ formatDate($event->event_day) }}</td>
                <td class="text-center">{{ $event->subscribes->count() }}</td>
                <td class="text-center">{{ formatDate($event->subscribe_begin) }} à
                    {{ formatDate($event->subscribe_end) }}</td>
                <td class="text-center">
                    <a href="{{ route('event.show', $event->id) }}" class="btn btn-sm btn-info"
                        title="Visualizar evento" data-toggle="tooltip" data-placement="top" role="button">
                        <i class="fa fa-info-circle"></i>
                    </a>
                    <a href="{{ route('event.edit', $event->id) }}" class="btn btn-sm btn-warning"
                        title="Alterar evento" data-toggle="tooltip" data-placement="top" role="button">
                        <i class="fas fa-pencil-alt"></i>
                    </a>
                    <button class="btn btn-sm btn-danger load-confirmation-modal" data-toggle="tooltip"
                        data-placement="top" title="Excluir evento" role="button"
                        data-url="{{ route('event.destroy', $event->id) }}" data-type="Evento"
                        data-name="{{ eventName($event->edition, $event->name) }}" data-target="#confirmation-modal"
                        data-toggle="modal">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <div class="alert alert-info text-center">Nenhum evento cadastrado.</div>
    @endif
</div>
@endsection

resources/views/admin/event/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <a class="btn btn-sm btn-info mb-1" data-toggle="tooltip" data-placement="top" title="Voltar" role="button"
           href="{{ route('event.index') }}">
            <i class="fas fa-arrow-left"></i>
            Voltar
        </a>
        <table class="table table-sm">
            <thead class="thead-dark">
            <tr>
                <th scope="col" class="text-center">#</th>
                <th scope="col" class="text-center">Evento</th>
                <th scope="col" class="text-center">Data</th>
                <th scope="col" class="text-center">Período de Inscrição</th>
                <th scope="col" class="text-center">Ações</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row" class="text-center">{{ $event->id }}</th>
                <td class="text-center">{{ eventName($event->edition, $event->name) }}</td>
                <td class="text-center">{{ formatDate($event->event_day) }}</td>
                <td class="text-center">{{ formatDate($event->subscribe_begin) }} à {{ formatDate($event->subscribe_end) }}</td>
                <td class="text-center">
                    <a href="{{ route('event.edit', $event->id) }}" class="btn btn-sm btn-warning" title="Alterar evento" data-toggle="tooltip" data-placement="top" role="button">
                        <i class="fas fa-pencil-alt"></i>
                    </a>
                </td>
            </tr>
            </tbody>
        </table>

        @if($event->subscribes->count() > 0)
            <table class="table table-sm">
                <thead class="thead-light">
                <tr>
                    <th scope="col" colspan="5" class="text-center">{{ $event->subscribes->count() }}
                        Inscrito{{ $event->subscribes->count() > 1 ? 's' : '' }}</th>
                </tr>
                <tr>
                    <th scope="col" class="text-center">#</th>
                    <th scope="col" class="text-center">Nome</th>
                    <th scope="col" class="text-center">E-mail</th>
                    <th scope="col" class="text-center">Telefone</th>
                    <th scope="col" class="text-center">Ações</th>
                </tr>
                </thead>
                <tbody>

                @foreach($event->subscribes as $subscribe)
                    <tr>
                        <th scope="row" class="text-center">{{ $subscribe->id }}</th>
                        <td class="text-center">{{ $subscribe->name }}</td>
                        <td class="text-center">{{ $subscribe->email }}</td>
                        <td class="text-center">{{ formatMobileNumber($subscribe->phone) }}</td>
                        <td class="text-center">
                            <a href="{{ route('subscribe.show', $subscribe->id) }}" class="btn btn-sm btn-info" title="Visualizar inscrito" data-toggle="tooltip" data-placement="top" role="button">
                                <i class="fas fa-info-circle"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @else
            <div class="alert alert-info text-center">Nenhuma pessoa inscrita neste evento.</div>
        @endif
    </div>




@endsection