routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


/** Rotas para usuários autenticados */
Route::middleware('auth')->group(function () {

    /** Rotas para painel administrativo */
    Route::prefix('admin')->group(function () {

        Route::get('home', 'HomeController@index')->name('home');

        /** Rotas para Event */
        Route::prefix('event')->name('event.')->group(function () {
            Route::get('/', 'EventController@index')->name('index');
            Route::get('/create', 'EventController@create')->name('create');
            Route::post('/store', 'EventController@store')->name('store');
            Route::get('/edit/{event}', 'EventController@edit')->name('edit');
            Route::put('/update/{event}', 'EventController@update')->name('update');
            Route::delete('/destroy/{event}', 'EventController@destroy')->name('destroy');
            Route::get('/show/{event}', 'EventController@show')->name('show');
        });

        /** Rotas para Subscribe */
        Route::prefix('subscribe')->name('subscribe.')->group(function () {
            Route::get('/', 'SubscribeController@index')->name('index');
            Route::get('/show/{subscribe}', 'SubscribeController@show')->name('show');
        });
    });
});

/** Rotas públicas */
Route::prefix('web')->group(function () {

    /** Rotas para Subscribe */
    Route::prefix('subscribe')->name('subscribe.')->group(function () {
        Route::get('/create', 'SubscribeController@create')->name('create');
        Route::post('/store', 'SubscribeController@store')->name('store');
    });
});

app/Models/Subscribe.php
<?php

namespace Descolado\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Subscribe extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',
        'email',
        'phone',
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    public function events()
    {
        return $this->belongsToMany(Event::class, 'subscribe_events');
    }
}

app/Http/Controllers/SubscribeController.php
<?php

namespace Descolado\Http\Controllers;

use Descolado\Http\Controllers\Controller;
use Descolado\Http\Requests\SubscribeRequest;
use Descolado\Interfaces\Repositories\SubscribeRepositoryInterface;

class SubscribeController extends Controller
{

    /**
     * @var SubscribeRepositoryInterface
     */
    private $repository;

    /**
     * SubscribeController constructor.
     * @param SubscribeRepositoryInterface $repository
     */
    public function __construct(SubscribeRepositoryInterface $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $subscribes = $this->repository->getAllSubscribes();

        return view('admin.subscribe.index', compact('subscribes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.subscribe.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param SubscribeRequest $request
     * @return void
     */
    public function store(SubscribeRequest $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $subscribe = $this->repository->getEventById($id);

        return view('admin.subscribe.list', compact('subscribe'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return void
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param SubscribeRequest $request
     * @param  int $id
     * @return void
     */
    public function update(SubscribeRequest $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return void
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/subscribe/create.blade.php
@extends('welcome')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                {!! Form::open(['route' => 'subscribe.store']) !!}

                @include('admin.event._form')

                <div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        {!! Form::submit('Cadastrar', ['class' => 'btn btn-primary']) !!}
                        <a href="{{ route('event.index') }}" class="btn btn-dark">Cancelar</a>
                    </div>
                </div>

                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/subscribe/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @includeIf('layouts._confirmation-modal')
        @if($subscribes->count() > 0)
        <table class="table table-striped table-sm">
            <thead class="thead-dark">
            <tr>
                <th scope="col" class="text-center">#</th>
                <th scope="col" class="text-center">Nome</th>
                <th scope="col" class="text-center">E-mail</th>
                <th scope="col" class="text-center">Contato</th>
                <th scope="col" class="text-center">Eventos Inscritos</th>
                <th scope="col" class="text-center">Ações</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($subscribes as $subscribe)
                <tr>
                    <th scope="row" class="text-center">{{ $subscribe->id}}</th>
                    <td class="text-center">{{ $subscribe->name}}</td>
                    <td class="text-center">{{ $subscribe->email}}</td>
                    <td class="text-center">{{ formatMobileNumber($subscribe->phone) }}</td>
                    <td class="text-center">{{ $subscribe->events->count() }}</td>
                    <td class="text-center">
                        <a href="{{ route('subscribe.show', $subscribe->id) }}" class="btn btn-sm btn-info" title="Visualizar inscrito" data-toggle="tooltip" data-placement="top" role="button">
                            <i class="fas fa-info-circle"></i>
                        </a>
                        {{--<a href="#" class="btn btn-sm btn-warning" title="Alterar inscrito" data-toggle="tooltip" data-placement="top" role="button">--}}
                            {{--<i class="fas fa-pencil-alt"></i>--}}
                        {{--</a>--}}
                        {{--<button class="btn btn-sm btn-danger load-confirmation-modal" data-toggle="tooltip" data-placement="top" title="Remover inscrito" role="button" data-url="#" data-type="Inscrito" data-name="{{ $subscribe->name }}" data-target="#confirmation-modal" data-toggle="modal">--}}
                            {{--<i class="fas fa-trash-alt"></i>--}}
                        {{--</button>--}}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        @else
        <div class="alert alert-info text-center">Nenhum inscrito cadastrado.</div>
        @endif
    </div>
@endsection

resources/views/admin/subscribe/list.blade.php
    @extends('layouts.app')

@section('content')
    <div class="container">
        <a class="btn btn-sm btn-info mb-1" data-toggle="tooltip" data-placement="top" title="Voltar" role="button"
           href="{{ route('subscribe.index') }}">
            <i class="fas fa-arrow-left"></i>
            Voltar
        </a>
        <table class="table table-sm">
            <thead class="thead-dark">
            <tr>
                <th scope="col" class="text-center">#</th>
                <th scope="col" class="text-center">Nome</th>
                <th scope="col" class="text-center">E-mail</th>
                <th scope="col" class="text-center">Telefone</th>
                <th scope="col" class="text-center">Ações</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row" class="text-center">{{ $subscribe->id }}</th>
                <td class="text-center">{{ $subscribe->name }}</td>
                <td class="text-center">{{ $subscribe->email }}</td>
                <td class="text-center">{{ formatMobileNumber($subscribe->phone) }}</td>
                <td class="text-center">
                    <a href="#" class="btn btn-sm btn-warning" title="Alterar inscrito" data-toggle="tooltip" data-placement="top" role="button">
                        <i class="fas fa-pencil-alt"></i>
                    </a>
                </td>

            </tr>
            </tbody>
        </table>

        @if($subscribe->events->count() > 0)
            <table class="table table-sm">
                <thead class="thead-light">
                <tr>
                    <th scope="col" colspan="5" class="text-center">{{ $subscribe->events->count() }}
                        Evento{{ $subscribe->events->count() > 1 ? 's' : '' }}</th>
                </tr>
                <tr>
                    <th scope="col" class="text-center">#</th>
                    <th scope="col" class="text-center">Evento</th>
                    <th scope="col" class="text-center">Data</th>
                    <th scope="col" class="text-center">Período de Inscrição</th>
                    <th scope="col" class="text-center">Ações</th>
                </tr>
                </thead>
                <tbody>

                @foreach($subscribe->events as $event)
                    <tr>
                        <th scope="row" class="text-center">{{ $event->id }}</th>
                        <td class="text-center">{{ eventName($event->edition, $event->name) }}</td>
                        <td class="text-center">{{ formatDate($event->event_day) }}</td>
                        <td class="text-center">{{ formatDate($event->subscribe_begin) }} à {{ formatDate($event->subscribe_end) }}</td>
                        <td class="text-center">
                            <a href="{{ route('event.show', $event->id) }}" class="btn btn-sm btn-info" title="Visualizar evento" data-toggle="tooltip" data-placement="top" role="button">
                                <i class="fas fa-info-circle"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @else
            <div class="alert alert-info text-center">Nenhum evento para este inscrito.</div>
        @endif
    </div>




@endsection