routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


/** Rotas para usuários autenticados */
Route::middleware('auth')->group(function () {

    /** Rotas para painel administrativo */
    Route::prefix('admin')->group(function () {

        Route::get('home', 'HomeController@index')->name('home');

        /** Rotas para Event */
        Route::prefix('event')->name('event.')->group(function () {
            Route::get('/', 'EventController@index')->name('index');
            Route::get('/create', 'EventController@create')->name('create');
            Route::post('/store', 'EventController@store')->name('store');
            Route::get('/edit/{event}', 'EventController@edit')->name('edit');
            Route::put('/update/{event}', 'EventController@update')->name('update');
            Route::delete('/destroy/{event}', 'EventController@destroy')->name('destroy');
            Route::get('/show/{event}', 'EventController@show')->name('show');
        });

        /** Rotas para Subscribe */
        Route::prefix('subscribe')->name('subscribe.')->group(function () {
            Route::get('/', 'SubscribeController@index')->name('index');
            Route::get('/show/{subscribe}', 'SubscribeController@show')->name('show');
        });
    });
});

/** Rotas públicas */
Route::prefix('web')->group(function () {

    /** Rotas para Subscribe */
    Route::prefix('subscribe')->name('subscribe.')->group(function () {
        Route::get('/create', 'SubscribeController@create')->name('create');
        Route::post('/store', 'SubscribeController@store')->name('store');
    });
});

resources/views/layouts/_confirmation-modal.blade.php
<div class="modal fade" id="confirmation-modal" tabindex="-1" role="dialog" aria-labelledby="confirmation-modal-title">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p></p>
            </div>
            <div class="modal-footer">
                {!! Form::open(['url' => '', 'method' => 'POST']) !!}
                @method('DELETE')
                <button class="btn btn-sm btn-danger" type="submit">
                    <i class="fas fa-trash-alt"></i> Confirmar
                </button>
                <button type="button" class="btn btn-sm btn-dark" data-dismiss="modal">
                    <i class="fas fa-times"></i> Cancelar
                </button>
                {!! Form::close() !!}

            </div>
        </div>
    </div>
</div>

resources/views/layouts/_errors.blade.php
@if(!empty($errors->first($field)))
    {!! $errors->first($field, '<div class="invalid-feedback">:message</div>') !!}
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{{ asset('images/favicon.png') }}">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{{ route('home') }}">
                <img src="{{ asset('images/logo.png') }}" height="50">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            @auth()
                <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('event.index') }}">Eventos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('subscribe.index') }}">Inscritos</a>
                        </li>
                    </ul>
            @endauth
            <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        <div class="container-fluid">
            @yield('content')
        </div>
    </main>
</div>
@yield('after-script')
</body>
</html>